apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3-smart-browser.fullname" . }}
  labels:
    {{- include "s3-smart-browser.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "s3-smart-browser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "s3-smart-browser.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "s3-smart-browser.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "s3-smart-browser.fullname" . }}-config
                  key: AWS_REGION
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "s3-smart-browser.fullname" . }}-config
                  key: AWS_BUCKET
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "s3-smart-browser.fullname" . }}-config
                  key: SERVER_PORT
            {{- if .Values.config.aws.endpoint }}
            - name: AWS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "s3-smart-browser.fullname" . }}-config
                  key: AWS_ENDPOINT
            {{- end }}
            {{- if .Values.config.app.baseDirectory }}
            - name: BASE_DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "s3-smart-browser.fullname" . }}-config
                  key: BASE_DIRECTORY
            {{- end }}
            {{- if .Values.secrets.awsAccessKeyId }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "s3-smart-browser.fullname" . }}-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "s3-smart-browser.fullname" . }}-secrets
                  key: AWS_SECRET_ACCESS_KEY
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}