apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3-smart-browser.fullname" . }}
  labels:
    {{- include "s3-smart-browser.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "s3-smart-browser.selectorLabels" . | nindent 4 }}