name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/s3-smart-browser
        tags: |
          type=raw,value=latest
          type=ref,event=tag
          type=sha,prefix=

    - name: Get version info
      id: version
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          VERSION="${{ github.ref_name }}"
        else
          VERSION=$(git describe --tags --always --dirty)
        fi
        GIT_COMMIT="${{ github.sha }}"
        BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "GIT_COMMIT=$GIT_COMMIT" >> $GITHUB_OUTPUT
        echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        echo "Commit: $GIT_COMMIT"
        echo "Build time: $BUILD_TIME"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VERSION=${{ steps.version.outputs.VERSION }}
          GIT_COMMIT=${{ steps.version.outputs.GIT_COMMIT }}
          BUILD_TIME=${{ steps.version.outputs.BUILD_TIME }}