name: Publish Helm Chart

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  publish-helm:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Package Helm chart
      run: |
        helm package charts/s3-browser -d ./helm-packages --app-version ${{ github.ref_name }}

    - name: Upload Helm chart to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./helm-packages/s3-browser-*.tgz
        asset_name: s3-browser-${{ github.ref_name }}.tgz
        asset_content_type: application/gzip