name: Publish Helm Chart and Repository

on:
  release:
    types: [published]

jobs:
  publish-helm:
    name: Publish Helm Chart and Update Repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Package Helm chart
      id: package
      run: |
        mkdir -p ./helm-packages
        helm package charts/s3-smart-browser -d ./helm-packages --app-version ${{ github.ref_name }}
        echo "chart_file=$(ls ./helm-packages/s3-smart-browser-*.tgz)" >> $GITHUB_OUTPUT

    - name: Download existing index.yaml (if any)
      run: |
        # Try to download existing index to merge with new package
        curl -f -L -o existing-index.yaml https://blackojack.github.io/s3-smart-browser/index.yaml || echo "No existing index.yaml found"

    - name: Generate or update index.yaml
      run: |
        if [ -f existing-index.yaml ]; then
          helm repo index ./helm-packages --url https://blackojack.github.io/s3-smart-browser --merge existing-index.yaml
        else
          helm repo index ./helm-packages --url https://blackojack.github.io/s3-smart-browser
        fi

    - name: Upload Helm chart to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.package.outputs.chart_file }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./helm-packages/

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4