name: Publish Helm Chart

on:
  release:
    types: [published]

jobs:
  publish-helm:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Package Helm chart
      id: package
      run: |
        mkdir -p ./helm-packages
        helm package charts/s3-smart-browser -d ./helm-packages --app-version ${{ github.ref_name }}
        echo "chart_file=$(ls ./helm-packages/s3-smart-browser-*.tgz)" >> $GITHUB_OUTPUT

    - name: Upload Helm chart to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.package.outputs.chart_file }}
        asset_name: s3-smart-browser-${{ github.ref_name }}.tgz
        asset_content_type: application/gzip