# name: Security Scan

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   schedule:
#     - cron: '0 0 * * 0' # Weekly

# jobs:
#   trivy-scan:
#     name: Vulnerability Scan
#     runs-on: ubuntu-latest
    
#     permissions:
#       contents: read
#       security-events: write

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Run Trivy vulnerability scanner
#       uses: aquasecurity/trivy-action@master
#       with:
#         scan-type: 'fs'
#         scan-ref: '.'
#         format: 'sarif'
#         output: 'trivy-results.sarif'

#     - name: Upload Trivy scan results to GitHub Security tab
#       uses: github/codeql-action/upload-sarif@v2
#       with:
#         sarif_file: 'trivy-results.sarif'

#   hadolint-scan:
#     name: Dockerfile Lint
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Run Hadolint
#       uses: hadolint/hadolint-action@v3.1.0
#       with:
#         dockerfile: Dockerfile
#         format: sarif
#         output-file: hadolint-results.sarif

#     - name: Upload Hadolint results
#       uses: github/codeql-action/upload-sarif@v2
#       with:
#         sarif_file: 'hadolint-results.sarif'